### ISSUE TITLE
Changing Random to False Doesn't Work

### ISSUE THREAD

**Issue by crystalrubik** [cdig/q-n-eh#6]
Changing "random" : "false" doesn't work. Questions are still random. If the "random" line is deleted, it works to stop randomizing. Just seems like we should be able to put "false" in and have it work.

**Comment by ivanreese** [comment]
Agreed.

On a meta note: the "bug" and "enhancement" labels are somewhat mutually exclusive. This is definitely a bug, either in the implementation or the documentation. An enhancement would be a wholly new feature.

**Comment by crystalrubik** [comment]
I wasn't sure if this was on purpose or how json worked (I noticed this same bug in flash q'n'a as well with framed)... so I chose both ;)

**Comment by ivanreese** [comment]
Great question. It's not how JSON works, it's just Sean or I being vague in how we implement it, haha. In most cases, setting something like that to false or null should be the same as just not giving a value, unless the documentation says otherwise. So either it's a bug in the implementation because we were rushing, or a bug in the documentation in that it should explain the behaviour more clearly.

**Comment by crystalrubik** [comment]
Cool, well it will be nice to use false then. :) It would be hard to remember to delete the line instead.

**Comment by theseanzo** [comment]
Works! Not sure when it was fixed, but it works.

**Comment by iMcKelvie** [comment]
Crystal and I have both run updates on our projects, and then tried setting the line to read 
`"random" : "false",`
it still randomizes, though.

**Comment by theseanzo** [comment]
Not a string!
